import { z } from 'zod';

export const inventoryLedgerListQuerySchema = z.object({
  current: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(1000).default(20),
  q: z.string().trim().max(120).optional(),
  item_id: z.string().trim().max(80).optional(),
  item_code: z.string().trim().max(120).optional(),
  item_name: z.string().trim().max(160).optional(),
  project_id: z.string().trim().max(80).optional(),
  project_code: z.string().trim().max(120).optional(),
  customer_id: z.string().trim().max(80).optional(),
  customer_name: z.string().trim().max(160).optional(),
  warehouse_id: z.string().trim().max(40).optional(),
  warehouse_ids: z.string().trim().max(500).optional(),
  location_id: z.string().trim().max(80).optional(),
  location_code: z.string().trim().max(120).optional(),
  inventory_status: z.string().trim().max(40).optional(),
  inventory_statuses: z.string().trim().max(500).optional(),
  transaction_type: z.string().trim().max(80).optional(),
  transaction_types: z.string().trim().max(500).optional(),
  source_no: z.string().trim().max(120).optional(),
  source_type: z.string().trim().max(120).optional(),
  operator_name: z.string().trim().max(120).optional(),
  quantity_min: z.coerce.number().optional(),
  quantity_max: z.coerce.number().optional(),
  updated_from: z.string().trim().max(40).optional(),
  updated_to: z.string().trim().max(40).optional(),
  occurred_from: z.string().trim().max(40).optional(),
  occurred_to: z.string().trim().max(40).optional(),
  sort_by: z.string().trim().max(80).optional(),
  sort_order: z.enum(['asc', 'desc']).optional(),
  abnormal_only: z.coerce.boolean().optional(),
  overdue_only: z.coerce.boolean().optional(),
  low_stock_only: z.coerce.boolean().optional(),
});
